hello_world/urls.py
from django.urls import path

from . import views
app_name = 'hello_world'
urlpatterns = [
    path("", views.index, name="index"),
]

kadai/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello_world/', include('hello_world.urls')),
    path('kimetu/', include('kimetu.urls')),
]

kimetu/urls.py
from django.urls import path
from . import views

app_name = "kimetu"
urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("display", views.display, name="display"),
]

hello_world/models.py
from django.db import models

# Create your models here.

kimetu/models.py
from django.db import models

# Create your models here.

GENDER_CHOICES = (
    ("男", "男"),
    ("女", "女"),
)


class Character(models.Model):
    name = models.CharField("名前", max_length=2048)
    gender = models.CharField("性別", choices=GENDER_CHOICES, max_length=250)
    feature = models.CharField("特徴", max_length=2048)

    def __str__(self):
        return self.name


class Gender(models.Model):
    gender = models.CharField("性別", choices=GENDER_CHOICES, max_length=250)

    def __str__(self):
        return self.gender

kimetu/forms.py
from .models import Character, Gender
from django import forms


class CharacterForm(forms.ModelForm):
    gender = forms.ModelChoiceField(Gender.objects, label="性別")

    class Meta:
        model = Character
        fields = ("name", "gender", "feature")

hello_world/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'hello_world/index.html')

kimetu/views.py
from django.shortcuts import render, redirect
from .models import Character
from .forms import CharacterForm

# Create your views here.


def index(request):
    return render(request, "kimetu/top.html")


def display(request):
    all_data = Character.objects.all()
    return render(request, "kimetu/display.html", {"all_data": all_data})


def register(request):
    print(request.body)
    params = {"message": "", "form": None}
    if request.method == "POST":
        form = CharacterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/kimetu/display")
        else:
            params["message"] = "再入力して下さい"
            params["form"] = form
    else:
        params["form"] = CharacterForm()
    return render(request, "kimetu/register.html", params)

hello_world/templates/hello_world/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>kadai</title>
</head>
<body>
  <h1>hello world</h1>
</body>
</html>

kimetu/templates/kimetu/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'kimetu/base_style.css' %}">
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>
<body>
  <div id="wrap_content">
    <div id="right_sidebar">
      {% block right_sidebar %}
      {% endblock %}
    </div>
    <div id="main_content">
      {% block main_content %}
      {% endblock %}
    </div>
    <div id="left_sidebar">
      {% block left_sidebar %}
      {% endblock %}
    </div>
  </div>
</body>
</html>

kimetu/templates/kimetu/display.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'kimetu/display_style.css' %}">
  <title>キャラクターリスト</title>
</head>
<body>
  <h2>登録キャラクターリスト</h2>
  <ul>
    {% for item in all_data %}
    <li>名前:{{ item.name}}</li>
    <li style="list-style: none;">性別:{{ item.gender}}</li>
    <li style="list-style: none;">特徴:{{ item.feature}}</li>
    {% endfor %}
  </ul>
</body>
</html>

kimetu/templates/kimetu/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>register</title>
</head>
<body>
  <h1>キャラクター登録ページ</h1>
  <form action="{% url 'kimetu:register' %}" method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">送信</button>
  </form>
  <p>{{ message }}</p>
</body>
</html>

kimetu/templates/kimetu/top.html
{% extends 'kimetu/base.html' %}
{% block title %}
トップページ
{% endblock %}
{% block right_sidebar %}
<ul>
  <li><a href="{% url 'kimetu:register' %}">登録フォーム</a></li>
</ul>
{% endblock %}
{% block main_content %}
<h2>トップページ</h2>
{% endblock main_content %}
{% block left_sidebar %}
<ul>
  <li><a href="{% url 'kimetu:display' %}">キャラクターリスト一覧</a></li>
</ul>
{% endblock %}